### ISSUE TITLE
Key Not in Region

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tikv-client-java#126]
```Caused by: com.pingcap.tikv.exception.SelectException: unknown error Mvcc(Engine(Request(message: "key is not in region" key_not_in_region {key: "t\200\000\000\000\000\000\000\377H_r\200\000\000\000\036\377\233\370g\000\000\000\000\000\372" region_id: 35066 start_key: "t\200\000\000\000\000\000\000\377H_r\200\000\000\000\036\377\271\356\202\000\000\000\000\000\372" end_key: "t\200\000\000\000\000\000\000\377H_r\200\000\000\000\036\377\312f\240\000\000\000\000\000\372"})))
  at com.pingcap.tikv.region.RegionStoreClient.coprocessorHelper(RegionStoreClient.java:192)
  at com.pingcap.tikv.region.RegionStoreClient.coprocess(RegionStoreClient.java:185)
  at com.pingcap.tikv.operation.SelectIterator.createClientAndSendReq(SelectIterator.java:130)
  at com.pingcap.tikv.operation.SelectIterator.lambda$submitTasks$2(SelectIterator.java:113)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  ... 3 more
````
Above error seems not handled properly. Likely due to region change but cache not correctly purged.

**Comment by zhexuany** [comment]
Agree. such execution need to be caught instead of ignoring. It is hard to reproduce... Tried several time.

**Comment by ilovesoup** [comment]
In a real env it's hard but if you just fake the data, easy.

**Comment by ilovesoup** [comment]
Fixed I believe. Please confirm @zhexuany

**Comment by zhexuany** [comment]
Confirmed.
