### ISSUE TITLE
Error handling TiConstant with value of null in range building

### ISSUE THREAD

**Issue by Novemser** [pingcap/tikv-client-java#137]
Run this query(column `tp_int` is `integer` type)
```
select tp_int from full_data_type_table where tp_int <> null
```
Throws 
```java
com.pingcap.tikv.exception.TiClientInternalException: Error converting access pointsnull
  at com.pingcap.tikv.predicates.RangeBuilder.exprsToPoints(RangeBuilder.java:80)
  at com.pingcap.tikv.predicates.RangeBuilder.exprsToIndexRanges(RangeBuilder.java:49)
  at com.pingcap.tikv.predicates.ScanBuilder.buildScan(ScanBuilder.java:116)
  at com.pingcap.tikv.predicates.ScanBuilder.buildTableScan(ScanBuilder.java:98)
  at org.apache.spark.sql.TiStrategy.filterToSelectRequest(TiStrategy.scala:120)
  at org.apache.spark.sql.TiStrategy.pruneFilterProject(TiStrategy.scala:145)
  at org.apache.spark.sql.TiStrategy.org$apache$spark$sql$TiStrategy$$doPlan(TiStrategy.scala:207)
  at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:57)
  at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:55)
---dummy stack trace ignored---
```

Seems there's some issue with `accessPoints` we extracted for request construction.

**Comment by ilovesoup** [comment]
Thx for finding it. 我的锅

**Comment by Novemser** [comment]
Another crash example:
`select count(id_dt) from full_data_type_table where tp_tinyint > 'PingCAP' limit 1`
Throws:
```java
com.pingcap.tikv.exception.TiClientInternalException: Error converting access pointsnull
  at com.pingcap.tikv.predicates.RangeBuilder.exprsToPoints(RangeBuilder.java:80)
  at com.pingcap.tikv.predicates.RangeBuilder.exprsToIndexRanges(RangeBuilder.java:49)
  at com.pingcap.tikv.predicates.ScanBuilder.buildScan(ScanBuilder.java:116)
  at com.pingcap.tikv.predicates.ScanBuilder.buildTableScan(ScanBuilder.java:98)
  at org.apache.spark.sql.TiStrategy.filterToDAGRequest(TiStrategy.scala:120)
  at org.apache.spark.sql.TiStrategy.org$apache$spark$sql$TiStrategy$$doPlan(TiStrategy.scala:262)
  at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:58)
  at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:56)
```

**Comment by Novemser** [comment]
Fixed
