### ISSUE TITLE
protocol for how to update region's leader need fix

### ISSUE THREAD

**Issue by zhexuany** [pingcap/tikv-client-java#88]
stack tree is the following:

```
Driver stacktrace:
  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1918)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1981)
  at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1025)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.reduce(RDD.scala:1007)
  at org.apache.spark.rdd.RDD$$anonfun$takeOrdered$1.apply(RDD.scala:1428)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
  at org.apache.spark.rdd.RDD.takeOrdered(RDD.scala:1415)
  at org.apache.spark.sql.execution.TakeOrderedAndProjectExec.executeCollect(limit.scala:133)
  at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2371)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
  at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2765)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2370)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2377)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2113)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2112)
  at org.apache.spark.sql.Dataset.withTypedCallback(Dataset.scala:2795)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2112)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:2327)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:248)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:636)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:595)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:604)
  ... 70 elided
Caused by: com.pingcap.tikv.exception.TiClientInternalException: Error Closing Store client.
  at com.pingcap.tikv.operation.SelectIterator.createClientAndSendReq(SelectIterator.java:87)
  at com.pingcap.tikv.operation.SelectIterator.readNextRegion(SelectIterator.java:109)
  at com.pingcap.tikv.operation.SelectIterator.hasNext(SelectIterator.java:122)
  at com.pingcap.tispark.TiRDD$$anon$1.hasNext(TiRDD.scala:67)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
  at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:126)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
  at org.apache.spark.scheduler.Task.run(Task.scala:99)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:748)
Caused by: com.pingcap.tikv.exception.GrpcException: com.google.guava4pingcap.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
  at com.pingcap.tikv.policy.RetryPolicy.callWithRetry(RetryPolicy.java:73)
  at com.pingcap.tikv.AbstractGrpcClient.callWithRetry(AbstractGrpcClient.java:56)
  at com.pingcap.tikv.region.RegionStoreClient.coprocess(RegionStoreClient.java:246)
  at com.pingcap.tikv.operation.SelectIterator.createClientAndSendReq(SelectIterator.java:79)
  ... 14 more
Caused by: com.google.guava4pingcap.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
  at com.google.guava4pingcap.cache.LocalCache$Segment.get(LocalCache.java:2207)
  at com.google.guava4pingcap.cache.LocalCache.get(LocalCache.java:3953)
  at com.google.guava4pingcap.cache.LocalCache.getOrLoad(LocalCache.java:3957)
  at com.google.guava4pingcap.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
  at com.google.guava4pingcap.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4881)
  at com.pingcap.tikv.region.RegionManager.updateLeader(RegionManager.java:172)
  at com.pingcap.tikv.operation.KVErrorHandler.handle(KVErrorHandler.java:54)
  at com.pingcap.tikv.policy.RetryPolicy.callWithRetry(RetryPolicy.java:64)
  ... 17 more
Caused by: java.lang.NullPointerException
  at com.pingcap.tikv.kvproto.Pdpb$GetRegionByIDRequest$Builder.setHeader(Pdpb.java:12469)
  at com.pingcap.tikv.PDClient.getRegionByIDAsync(PDClient.java:128)
  at com.pingcap.tikv.region.RegionManager$1.load(RegionManager.java:65)
  at com.pingcap.tikv.region.RegionManager$1.load(RegionManager.java:62)
  at com.google.guava4pingcap.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
  at com.google.guava4pingcap.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
  at com.google.guava4pingcap.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
  at com.google.guava4pingcap.cache.LocalCache$Segment.get(LocalCache.java:2201)
  ... 24 more
```

**Comment by zhexuany** [comment]
The useful stack tree is 
```
Caused by: java.lang.NullPointerException
  at com.pingcap.tikv.kvproto.Pdpb$GetRegionByIDRequest$Builder.setHeader(Pdpb.java:12469)
  at com.pingcap.tikv.PDClient.getRegionByIDAsync(PDClient.java:128)
  at com.pingcap.tikv.region.RegionManager$1.load(RegionManager.java:65)
```

Header is null, when we try to set it in Request Builder.

**Comment by zhexuany** [comment]
working on it.
