### ISSUE TITLE
Exception: UNKNOWN: invalid zero store id

### ISSUE THREAD

**Issue by zhexuany** [pingcap/tikv-client-java#90]
```
Caused by: com.pingcap.tikv.exception.GrpcException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNKNOWN: invalid zero store id
  at com.pingcap.tikv.region.RegionManager.getStoreById(RegionManager.java:144)
  at com.pingcap.tikv.region.RegionManager.getRegionStorePairByKey(RegionManager.java:129)
  at com.pingcap.tikv.util.RangeSplitter.splitRangeByRegion(RangeSplitter.java:125)
  at com.pingcap.tispark.TiRDD.getPartitions(TiRDD.scala:77)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.ShuffleDependency.<init>(Dependency.scala:91)
  at org.apache.spark.sql.execution.exchange.ShuffleExchange$.prepareShuffleDependency(ShuffleExchange.scala:261)
  at org.apache.spark.sql.execution.exchange.ShuffleExchange.prepareShuffleDependency(ShuffleExchange.scala:84)
  at org.apache.spark.sql.execution.exchange.ShuffleExchange$$anonfun$doExecute$1.apply(ShuffleExchange.scala:121)
  at org.apache.spark.sql.execution.exchange.ShuffleExchange$$anonfun$doExecute$1.apply(ShuffleExchange.scala:112)
  at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)
  ... 211 more
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNKNOWN: invalid zero store id
  at com.google.guava4pingcap.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
  at com.google.guava4pingcap.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
  at com.google.guava4pingcap.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
  at com.pingcap.tikv.region.RegionManager.getStoreById(RegionManager.java:142)
  ... 239 more
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: invalid zero store id
  at io.grpc.Status.asRuntimeException(Status.java:543)
  at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
  at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
  at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
  at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
  at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
  at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
  at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
  at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:748)
```

**Comment by zhexuany** [comment]
This exception still happens from time to time, but spark is recoverable now from this kinda exception. Closing it for now. Feel free to reopen it if something goes wrong in future.
